encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<title>/", views.entry, name="wiki"),
    path("search/", views.search, name="search"),
    path("random/", views.random_page, name="random"),
    path("new/", views.new, name="new"),
    path("edit/", views.edit, name="edit"),
    path("save_edit/", views.save_edit, name="save_edit"),
    path("error/", views.error, name="error"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include("encyclopedia.urls", namespace="encyclopedia")),
    path('admin/', admin.site.urls),
]

encyclopedia/models.py
from django.db import models
from django.db.models.fields import CharField, TextField

# Create your models here.
class Entry(models.Model):
    title = CharField(max_length=120)
    content = TextField(blank=True)

encyclopedia/views.py
from typing import NoReturn
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django import forms
from django.urls import reverse
from . import util
from .models import Entry
import random
import re
import markdown2


class SearchForm(forms.Form):
    query = forms.CharField(min_length=1,
                            label='',
                            widget=forms.TextInput(attrs={
                                'size': '20',
                                'autocomplete': 'off',
                                'placeholder': 'Search Encyclopedia'
                            }
                            ))


class EditForm(forms.Form):
    article = forms.CharField(min_length=10,
                              label='',
                              widget=forms.Textarea(attrs={
                                  'autocomplete': 'off',
                                  'placeholder': 'Add Entry in Markdown'
                              }
                              ))


def index(request):
    context = {
        "entries": util.list_entries(),
        "form": SearchForm(),
    }
    return render(request, "encyclopedia/index.html", context)


def entry(request, title):
    if request.method in ["GET", "POST"]:
        titles = util.list_entries()
        if title in titles:
            context = {
                "title": title,
                "content": markdown2.markdown(util.get_entry(title)),
                "form": SearchForm(),
            }
            return render(request, "encyclopedia/entry.html", context)
        else:
            return HttpResponseRedirect(reverse('encyclopedia:error'))


def search(request):
    form = SearchForm(request.POST)
    matches = []
    if form.is_valid():
        query = form.cleaned_data["query"]
        entries = util.list_entries()
        # compile regex up here so it is cached, no need to recompile each iteration
        r = re.compile(rf"({query})", re.IGNORECASE)
        for entry in entries:
            if query.lower() == entry.lower():
                return HttpResponseRedirect(reverse('encyclopedia:wiki', kwargs={"title": entry}))
            else:
                # if no exact match, run regex search, append matches to list, return list
                match = r.search(entry)
                if match:
                    matches.append(entry)
        # if we have any matches
        if len(matches) > 0:
            return render(request, "encyclopedia/search.html", {
                "entries": matches,
                "form": SearchForm(),
            })
        # if there are no matches
        else:
            return HttpResponseRedirect(reverse('encyclopedia:error'))


def random_page(request):
    entries = util.list_entries()
    rand = random.randint(0, len(entries)-1)
    title = entries[rand]
    return HttpResponseRedirect(reverse('encyclopedia:wiki', kwargs={"title": title}))


def new(request):
    if request.method == "POST":
        form = EditForm(request.POST)
        if form.is_valid():
            article = form.cleaned_data["article"]
            title = article.split("\n")[0].strip("#").strip()
            util.save_entry(title, article)
            obj = Entry(title=f"{title}", content=f"{article}")
            obj.save()
        return HttpResponseRedirect(reverse('encyclopedia:wiki', kwargs={"title": title}))

    return render(request, "encyclopedia/new.html", {
        "form": SearchForm(),
        "edit_form": EditForm()
    })


def edit(request):
    if request.method == "POST":
        title = request.POST.get("edit").strip("Edit ")
        content = util.get_entry(title)
        initial = {'article': f'{content}'}
        return render(request, "encyclopedia/edit.html", {
            "title": title,
            "edit_form": EditForm(initial=initial),
            "form": SearchForm(),
        })


def save_edit(request):
    if request.method == "POST":
        form = EditForm(request.POST)
        if form.is_valid():
            article = form.cleaned_data["article"]
            title = article.split("\n")[0].strip("#").strip()
            util.save_entry(title, article)
        return HttpResponseRedirect(reverse('encyclopedia:wiki', kwargs={"title": title}))


def error(request):
    return render(request, "encyclopedia/error.html", {
        "form": SearchForm(),
    })

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit {{ title }}
{% endblock %}

{% block body %}
<h1>Edit Article</h1>

<form action="{% url 'encyclopedia:save_edit' %}" method="POST">
    {% csrf_token %}
    {{ edit_form }}
    <br>
    <input type="submit" name="edit" id="edit" value="Submit edits">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}

<p>{{ content|safe }}</p>

<br>

<form action="{% url 'encyclopedia:edit' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="edit" value="{{ title }}" hidden>
    <input type="submit" name="edit" id="submit" value="Edit {{ title }}">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Error
{% endblock %}

{% block body %}
<h1>Error</h1>

<h3>That entry could not be found</h3>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Main
{% endblock %}

{% block body %}

    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>
                <a href="{% url 'encyclopedia:wiki' entry %}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>Encyclopedia: {% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>

                <form action="{% url 'encyclopedia:search' %}" method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" name="submit" id="submit">
                </form>
                
                <a href="{% url 'encyclopedia:index' %}">Home</a>
                <br>
                <a href="{% url 'encyclopedia:new' %}">Create New Page</a>
                <br>
                <a href="{% url 'encyclopedia:random' %}">Random Page</a>

                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
New Entry
{% endblock %}

{% block body %}
<h1>Add New Article</h1>

<form action="{% url 'encyclopedia:new' %}" method="POST">
    {% csrf_token %}
    {{ edit_form }}
    <br>
    <input type="submit" name="submit" id="submit">
</form>


{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}
<h1>Search Results</h1>

<ul>
    {% for entry in entries %}
    <li>
        <a href="{% url 'encyclopedia:wiki' entry %}">{{ entry }}</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}